version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"
    environment:
      STORAGE_TYPE: mem
    networks:
      - zipkin-net

networks:
  zipkin-net:
    driver: bridge
