version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # HTTP collector
      - "14250:14250"  # gRPC collector
      - "6831:6831/udp"   # UDP agent
      - "6832:6832/udp"   # UDP agent
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - jaeger-net

networks:
  jaeger-net:
    driver: bridge
